# TCL File Generated by Component Editor 25.1
# Thu Feb 26 23:43:30 CET 2026
# DO NOT MODIFY


#
# jtag_reset_pulse "JTAG Reset Pulse" v1.0
# en 2026.02.26.23:43:30
# Minimal reset combiner for systems with an existing top-level reset
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module jtag_reset_pulse
#
set_module_property DESCRIPTION "Minimal reset combiner for systems with an existing top-level reset"
set_module_property NAME jtag_reset_pulse
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Custom_IP
set_module_property AUTHOR en
set_module_property DISPLAY_NAME "JTAG Reset Pulse"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL jtag_reset_pulse
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file jtag_reset_pulse.vhd VHDL PATH hdl/jtag_reset_pulse.vhd TOP_LEVEL_FILE


#
# parameters
#


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset_jtag
#
add_interface reset_jtag reset end
set_interface_property reset_jtag associatedClock clock
set_interface_property reset_jtag synchronousEdges DEASSERT
set_interface_property reset_jtag ENABLED true
set_interface_property reset_jtag EXPORT_OF ""
set_interface_property reset_jtag PORT_NAME_MAP ""
set_interface_property reset_jtag CMSIS_SVD_VARIABLES ""
set_interface_property reset_jtag SVD_ADDRESS_GROUP ""

add_interface_port reset_jtag i_jtag_reset reset_n Input 1


#
# connection point reset_sys
#
add_interface reset_sys reset end
set_interface_property reset_sys associatedClock clock
set_interface_property reset_sys synchronousEdges DEASSERT
set_interface_property reset_sys ENABLED true
set_interface_property reset_sys EXPORT_OF ""
set_interface_property reset_sys PORT_NAME_MAP ""
set_interface_property reset_sys CMSIS_SVD_VARIABLES ""
set_interface_property reset_sys SVD_ADDRESS_GROUP ""

add_interface_port reset_sys i_reset_n reset_n Input 1


#
# connection point reset_cpu
#
add_interface reset_cpu reset start
set_interface_property reset_cpu associatedClock clock
set_interface_property reset_cpu associatedDirectReset ""
set_interface_property reset_cpu associatedResetSinks reset_sys
set_interface_property reset_cpu synchronousEdges DEASSERT
set_interface_property reset_cpu ENABLED true
set_interface_property reset_cpu EXPORT_OF ""
set_interface_property reset_cpu PORT_NAME_MAP ""
set_interface_property reset_cpu CMSIS_SVD_VARIABLES ""
set_interface_property reset_cpu SVD_ADDRESS_GROUP ""

add_interface_port reset_cpu o_cpu_reset_n reset_n Output 1
