# {name}.sdc -- Timing constraints for DE10-Lite (MAX10)
# Generated by quartus-workflow setup. Edit as needed.

# 50 MHz system clock on MAX10_CLK1_50 (PIN_P11)
create_clock -period 20.000 -name clk [get_ports {MAX10_CLK1_50}]

# Allow TimeQuest to derive clock uncertainty automatically
derive_clock_uncertainty
