// {name}_top.v  Top-level module for {name} project (DE10-Lite)
// Generated by quartus-workflow setup. Edit as needed.

module {name}_top (
    input  wire        MAX10_CLK1_50,
    input  wire [1:0]  KEY,
    input  wire [9:0]  SW,
    output wire [9:0]  LEDR
);

// Platform Designer system instantiation
{name} u0 (
    .clk_clk       (MAX10_CLK1_50),
    .reset_reset_n (KEY[0])
);

endmodule
