-- {name}_top.vhd  Top-level entity for {name} project (DE10-Lite)
-- Generated by quartus-workflow setup. Edit as needed.

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity {name}_top is
    port (
        MAX10_CLK1_50 : in  std_logic;
        KEY           : in  std_logic_vector(1 downto 0);
        SW            : in  std_logic_vector(9 downto 0);
        LEDR          : out std_logic_vector(9 downto 0)
    );
end entity {name}_top;

architecture rtl of {name}_top is

    component {name} is
        port (
            clk_clk       : in std_logic;
            reset_reset_n : in std_logic
        );
    end component {name};

begin

    u0 : {name}
        port map (
            clk_clk       => MAX10_CLK1_50,
            reset_reset_n => KEY(0)
        );

end architecture rtl;
